### ISSUE TITLE
How to retrieve struct tag in DecodeHook?

### ISSUE THREAD

**Issue by hgl** [mitchellh/mapstructure#104]
I want to decode file path to file content, since I can't rely on type to decide if I should decode or not, it seems I should check struct tag instead.

But from the source code there doesn't seems to be a way to do that in `DecodeHook`, which only receives a field value?

**Comment by mitchellh** [comment]
This is true, the recommended usage would be to use a custom type (or struct) and have the decodehook catch that type. For example see how we handle time.Time.
