### ISSUE TITLE
mapstructure.go:667: undefined: reflect.ArrayOf

### ISSUE THREAD

**Issue by gavmckee80** [mitchellh/mapstructure#106]
Hi,

I'm getting an issue when I use go get to install mapstructure

go get github.com/mitchellh/mapstructure
# github.com/mitchellh/mapstructure
src/github.com/mitchellh/mapstructure/mapstructure.go:667: undefined: reflect.ArrayOf

**Comment by mitchellh** [comment]
You may be using a very old version of Go perhaps. 

Can you verify you're using Go 1.5+? ArrayOf was introducing in Go 1.5. Note that it is idiomatic to use the latest version of Go (currently 1.9.3 as of writing) at any given time since upgrading Go versions is very low risk.

**Comment by gavmckee80** [comment]
@mitchellh Thanks it was an old version of go causing the issue
