### ISSUE TITLE
Add a Tag for dep

### ISSUE THREAD

**Issue by monomosc** [mitchellh/mapstructure#110]
dep is a dependency manager for go. It has been started with the intention of being merged into the official toolchain and while I cannot really guess whether that's achievable, it is the tool that I and I believe the go community as a whole likes most for open-source package management.

It likes to operate on Releases/git tags, locking them in as constraints. If at all possible, I would like for this library to create a tag at a sensible commit and label it something sensible (like 1.0.0 if such versioning makes sense) to prevent users of mapstructure to either have to absolutely lock in a commit hash (as such preventing one from getting possible security updates) or a branch (prone to API breakage).

Thank you all for your time.

**Comment by chai2010** [comment]
add tag for vgo

**Comment by mitchellh** [comment]
Done v1.0.0 pushed and a `go.mod` file added (no deps though)
