### ISSUE TITLE
int64 support?

### ISSUE THREAD

**Issue by clausdenk** [mitchellh/mapstructure#114]
I just tried to convert a json file with unix timestamps, these are int64 in go. There seems to be no support for this data type, is this planned?

**Comment by sheerun** [comment]
same

**Comment by nswekosk** [comment]
Int64 is supported. You must use the `mapstructure` tag on the field.
ie.
```
type Result struct {
	ID           string   `json:"id"`
	Name         string   `json:"name"`
	Count int64    `mapstructure:"count",json:"audience_size"`
}
```

My JSON tags in the example are not required. If this does not solve your issue, please post an example JSON here and I would be open to providing feedback

**Comment by mitchellh** [comment]
As stated, this should work. If there is a repro anyone can give where it doesn't work please let me know.
