### ISSUE TITLE
Reconsider tagging repo 

### ISSUE THREAD

**Issue by mfridman** [mitchellh/mapstructure#126]
Hi,

Thank you for this pkg. Over the years it has remained stable and this issue is not out of fear of breaking changes.

Instead, as the Go community ~rallies behind vgo~ _adopts go modules_ it'd be nice for packages, especially commonly used ones, to be tagged appropriately. Issue #39 made it clear you don't have intentions of making breaking changes so a tag would be floccinaucinihilipilification (in good humor). 

Would you please reconsider adding a semver tag?

Instead of a go.mod reading like this:
```go
require (
	github.com/mitchellh/mapstructure v0.0.0-20180511142126-bb74f1db0675
)
```
It'd be:

```go
require (
	github.com/mitchellh/mapstructure v1.0.0
)
```

Thanks.

**Comment by mitchellh** [comment]
This is done!
