### ISSUE TITLE
json marshal of nested mapstructure

### ISSUE THREAD

**Issue by csandanov** [mitchellh/mapstructure#129]
I have structure `BuildMetadata` that used in `Config` (spf13/viper 1.0.0 config). For convenience I use the same structure in HTTP request payload. I marshal `Payload`, send the request and for some reason I get `RepoURL` in json instead of `repo_url`. What could be the issue?

```go
type BuildMetadata struct {
        // ....
	RepoUrl string `json,mapstructure:"repo_url"`
}

type Config struct {
        // ....
	Metadata      *types.BuildMetadata `json,mapstructure:"metadata"`
}

type Payload struct {
        // ....
	Metadata     *types.BuildMetadata `json:"info"`
}
```

**Comment by mfridman** [comment]
@csandanov Have you tried space-separating the tags? e.g.,

`json:"repo_url" mapstructure:"repo_url"`

It's redundant, but I _think_ it may solve the problem. Alternatively, you could override the default tag name with `DecoderConfig`, but depending on your needs this may be a bad solution.

```go
cfg := &mapstructure.DecoderConfig{
		TagName:          "json",
	}
```

and then pass `cgf` to `NewDecoder`

**Comment by alshdavid** [comment]
Can you set a config flag on `Decode` or another function like `DecodeAsJSON` to use existing `json` tags?

**Comment by mitchellh** [comment]
@mfridman got the result, closing!
