### ISSUE TITLE
reflect.Value.IsNil

### ISSUE THREAD

**Issue by hendrickcastro** [mitchellh/mapstructure#138]
goroutine 94 [running]:
reflect.Value.IsNil(0xe23920, 0xc04245dc80, 0x99, 0xe23900)
	C:/Go/src/reflect/value.go:1018 +0x19d
.../github.com/mitchellh/mapstructure.(*Decoder).decodePtr(0xc04209c038, 0xc958ab, 0x12, 0xe23920, 0xc04245dc80, 0xe24920, 0xc04246c230, 0x196, 0x0, 0x0)

The issue is on:

func (d *Decoder) decodePtr(name string, data interface{}, val reflect.Value) error {
	// If the input data is nil, then we want to just set the output
	// pointer to be nil as well.
-->	if data == nil || reflect.Indirect(reflect.ValueOf(data)).IsNil() {
		if !val.IsNil() && val.CanSet() {
			nilValue := reflect.New(val.Type()).Elem()
			val.Set(nilValue)
		}

		return nil

**Comment by mitchellh** [comment]
Fixed!
