### ISSUE TITLE
Type error when using DecodeHook to decode into interface

### ISSUE THREAD

**Issue by bastjan** [mitchellh/mapstructure#140]
**What version of are you using (git log -1 --format=oneline)?**
fe40af7a9c397fa3ddba203c38a5042c5d0475ad (HEAD -> master, tag: v1.1.1, origin/master, origin/HEAD) Update CHANGELOG

**What did you do?**
Run attached test:
```go
package mapstructure_test

import (
	"reflect"
	"testing"

	"github.com/mitchellh/mapstructure"
)

type DecodeInto struct {
	Test Interface
}

type Interface interface {
	DoStuff()
}

type ImplementsInterface struct {
	Name string
}

func (i *ImplementsInterface) DoStuff() {}

func TestInterfaceDecodeHook(t *testing.T) {
	in := map[string]string{"test": "test"}
	decodeInto := new(DecodeInto)

	config := &mapstructure.DecoderConfig{
		DecodeHook: stringToInterfaceDecodeHook,
		Result:     decodeInto,
	}
	decoder, _ := mapstructure.NewDecoder(config)
	err := decoder.Decode(in)
	if err != nil {
		t.Errorf("Decode returned error: %s", err)
	}
}

func stringToInterfaceDecodeHook(from, to reflect.Type, data interface{}) (interface{}, error) {
	if from.Kind() != reflect.String {
		return data, nil
	}

	if to != reflect.TypeOf((*Interface)(nil)).Elem() {
		return data, nil
	}
	// Ensure interface is satisfied
	var impl Interface = &ImplementsInterface{data.(string)}
	return impl, nil
}
```

**What did you expect to see?**
I expected the test to pass.

**What did you see instead?**
```
Running tool: /usr/local/opt/go@1.11/bin/go test -timeout 30s github.com/mitchellh/mapstructure -run ^TestInterfaceDecodeHook$

--- FAIL: TestInterfaceDecodeHook (0.00s)
    /Users/sebastianwidmer/go/src/github.com/mitchellh/mapstructure/mapstructure_interface_test.go:35: Decode returned error: 1 error(s) decoding:
        
        * 'Test' expected type 'mapstructure_test.Interface', got 'mapstructure_test.ImplementsInterface'
FAIL
FAIL	github.com/mitchellh/mapstructure	0.009s
Error: Tests failed.
```

This happens since upgrading to v1.1.1 to all our hooks decoding into interfaces. Will dig deeper into the changes tomorrow and try to create a pull request.

**Comment by bastjan** [comment]
No worries. Thanks for the great package.

The culprit is in https://github.com/mitchellh/mapstructure/commit/467034e73050ad4ebff943acfdf469d40bcc6e92#diff-80aa7a137566e62ca9976c661b2b1a65R319 and tested in "TestDecodeTable/basic_pointer_to_non-pointer".

Since the object is always stored dereferenced it can no longer implement interface methods with pointer style receivers.

```go
type StringerPointerReceiver struct{}

func (i *StringerPointerReceiver) String() string { return "" }

var _ fmt.Stringer = &StringerPointerReceiver{} // <- Works
var _ fmt.Stringer = StringerPointerReceiver{}  // <- Does not work
```

I see two possibilities to not break existing tests. Only dereference if receiver is `interface{}` and do nothing for programmer defined interfaces. The disadvantage is `type test interface{}` has different behaviour than `interface{}`.

```go
dataVal := reflect.ValueOf(data)
if val.Type() == reflect.TypeOf((*interface{})(nil)).Elem() {
	dataVal = reflect.Indirect(dataVal)
}
```

The other possibility I see is trying to assign pointer if by value does not work. This could lead to unexpected behavior if one type is assigned by reference and another by value at the same interface.
```go
if dataValType.AssignableTo(val.Type()) {
	val.Set(dataVal)
	return nil
} else if reflect.TypeOf(data).AssignableTo(val.Type()) {
	val.Set(reflect.ValueOf(data))
	return nil
} else {
	return fmt.Errorf(
		"'%s' expected type '%s', got '%s'",
		name, val.Type(), dataValType)
}
```

I'll create a merge request with my tests and both options implemented as individual commits. Maybe you have some additional ideas?

**Comment by bastjan** [comment]
Hi @mitchellh, I like your approach way better. I tried something similar but somehow missed a piece of the puzzle.

All our tests are green again with the version from master. Thanks a lot!

**Comment by mitchellh** [comment]
Great, I pushed a tagged release too.
