### ISSUE TITLE
Add options to use json names instead of member names

### ISSUE THREAD

**Issue by tonka3000** [mitchellh/mapstructure#142]
Hey,

I have a struct like this

```go
type A struct {
    DownloadURL string `json:"download_url`
}
```

My problem is that `Decode` use the member name (which is a good default). So when I have a json response where I have a `download_url` key, my struct value is empty.

It would be really nice if I can tell `Decode`to use the json names too.

Greetings  
Tonka

**Comment by casertap** [comment]
I need the exact same thing at the moment.
Here is a minimal example of what is happening:
```
package main

import "fmt"
import "github.com/mitchellh/mapstructure"

type LocationDecode struct {
	FreeShipping bool   `json:"free_shipping"`
	Logo         bool   `json:"logo"`
	MallCode     string `json:"mall_code"`
	AnotherOne   string `json:"another_one"`
	Name         string `json:"name"`
}

func main() {
	v := make(map[string]interface{})
	v["name"] = "test1"
	v["logo"] = false
	v["free_shipping"] = true
	v["mall_code"] = "test2"
	v["another_one"] = "test3"
	fmt.Println(v)
	result1 := LocationDecode{}
	errDecode := mapstructure.Decode(v, &result1)
	if errDecode != nil {
		fmt.Println(errDecode)
	}
	fmt.Println(result1)
}
```

output:
```
map[name:test1 logo:false free_shipping:true mall_code:test2 another_one:test3]
{false false   test1}
```
For some reason I have twice the value `false` but realy I had `logo:false free_shipping:true`
I only have the `name:test1` that has been extracted.

**Comment by casertap** [comment]
To work around this I have to make by `LocationDecode` struct like this:
```
type LocationDecode struct {
	Free_shipping bool
	Logo          bool
	Mall_code     string
	Another_one   string
	Name          string
}

```

**Comment by skynet2** [comment]
`	decResult := structs.DataServerResponseMessage{}
	test := map[string]string{
		"test_code": "321",
	}
	decConfig := mapstructure.DecoderConfig{
		TagName: "json",
		Result: &decResult,
		WeaklyTypedInput:true,
	}
	dec,err := mapstructure.NewDecoder(&decConfig)

	err = dec.Decode(test)`

This code should do the trick.

**Comment by casertap** [comment]
Thanks @skynet2 it works
