### ISSUE TITLE
expected a map, got 'struct'

### ISSUE THREAD

**Issue by renanberto** [mitchellh/mapstructure#149]
Hello guys, 
First, a great job was done here. This guy saves lives! :)

I am having a small problem in a struct to struct conversion. Apparently he's asking me for a map:

```.go
func (c *catalogRepository) GetUniqClient(client string) (models.Client, error) {
	var clients models.Client
	allClients, err := maestro.GetClient(client, c.config)
	if err != nil {
		return clients, err
	}
	err = mapstructure.Decode(&allClients, &clients)
	return clients, err
}
```

my two structs are so, and I just "mirror" with the method:

```.go

type Params map[string]string

type Client struct {
	ClientId            string     `json:"clientId"`
	AlternativeClientId string     `json:"alternativeClientId"`
	DataSource          DataSource `json:"dataSource"`
	BaseUrl             string     `json:"baseUrl"`
	WebVersion          string     `json:"webVersion"`
	AndroidVersion      string     `json:"androidVersion"`
	IosVersion          string     `json:"iosVersion"`
	Params              Params     `json:"params"`
	Active              bool       `json:"active"`
	PinCode             int        `json:"pinCode,omitempty"`
}

type DataSource struct {
	Url         string `json:"url"`
	Username    string `json:"username"`
	Password    string `json:"password"`
	InitialSize int    `json:"initialSize"`
	MaxActive   int    `json:"maxActive"`
	MaxIdle     int    `json:"maxIdle"`
	MinIdle     int    `json:"minIdle"`
}
```

## My return is:
`time="2018-12-08T11:26:35-02:00" level=fatal msg="Error to start the application.'' expected a map, got 'struct'"`

**Comment by renanberto** [comment]
I noticed that this method was changed recently:

https://github.com/mitchellh/mapstructure/blob/1225fbe39ade85da7786ef796dbad20231d66a67/mapstructure.go#L951

My values are the same, but he is not reflecting and consequently, it creates a map, but it is a struct.

**Comment by renanberto** [comment]
Dude, I tested it and that's it. I came back to change and followed correctly. I can not imagine why the reflect did not work, but it stays alert. I'll keep the lib out of date until you see it! Hugs!

CUT: 
```.go
       dataVal := reflect.ValueOf(data)

	// If the input data is a pointer, and the assigned type is the dereference
	// of that exact pointer, then indirect it so that we can assign it.
	// Example: *string to string
	if dataVal.Kind() == reflect.Ptr && dataVal.Type().Elem() == val.Type() {
		dataVal = reflect.Indirect(dataVal)
	}
```

PASTE:
```.go
	dataVal := reflect.Indirect(reflect.ValueOf(data))
```

**Comment by alexus1024** [comment]
Is struct-to-struct mapping supported by this library?
I suppose no. Only map-to-struct as mentioned in mapstructure.go:891

**Comment by renanberto** [comment]
Yes it's https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L962 

```.go
case reflect.Struct:
		// Not the most efficient way to do this but we can optimize later if
		// we want to. To convert from struct to struct we go to map first
		// as an intermediary.
		m := make(map[string]interface{})
		mval := reflect.Indirect(reflect.ValueOf(&m))
		if err := d.decodeMapFromStruct(name, dataVal, mval, mval); err != nil {
			return err
		}

		result := d.decodeStructFromMap(name, mval, val)
		return result
```

**Comment by mitchellh** [comment]
I tried with your example and everything worked for me. I'm unsure if I'm doing it wrong or if there is a test case I'm missing or we fixed in the past two years but I'm going to close this. If you can give me a repro case let me know. Note at the time of writing I tested against v1.4.0.
