### ISSUE TITLE
Decode into rune

### ISSUE THREAD

**Issue by bep** [mitchellh/mapstructure#151]
```go
type Decoder struct {
	// CSV options
	CSVComma   rune
	CSVComment rune
}
```

Decoding a map with a string into one of the above gives:

```bash
 strconv.ParseInt: parsing ";": invalid syntax
```

It would be good if you could check if target is `rune` and the rune count is 1 and then just set the value directly.

**Comment by mitchellh** [comment]
This sounds great but unfortunately is impossible because the Go reflect package can't distinguish between `rune` and `int32` (they're type aliases). So the current behavior is to attempt to parse the string as an integer. I think you'd have to use a custom type with a decode hook here, sorry!
