### ISSUE TITLE
type  time.Time Decode Error

### ISSUE THREAD

**Issue by lkx912343876** [mitchellh/mapstructure#159]
time.Time   Trans  from
struct->json->interface{}
then mapstructure   to time.Time  Error   
* 'Birty' expected a map, got 'string'
Code 
`import (
	"encoding/json"
	"fmt"
	"time"

	"github.com/mitchellh/mapstructure"
)

type TestTime struct {
	Name  string
	Birty time.Time
}

type Test struct {
	Flag int
	Data interface{}
}

func main() {
	d := TestTime{
		Name:  "hello",
		Birty: time.Now(),
	}
	test := Test{
		Flag: 1,
		Data: d,
	}
	jsv, _ := json.Marshal(test)
	fmt.Println(string(jsv))
	i := make(map[string]interface{})
	json.Unmarshal(jsv, &i)
	fmt.Println(i)
	r := TestTime{}
	err := mapstructure.Decode(i["Data"], &r)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(r)
	}
}`

result Is
`{"Flag":1,"Data":{"Name":"hello","Birty":"2019-04-03T11:20:50.3161803+08:00"}}
map[Flag:1 Data:map[Name:hello Birty:2019-04-03T11:20:50.3161803+08:00]]
1 error(s) decoding:

* 'Birty' expected a map, got 'string'`

**Comment by dohr-michael** [comment]
You need to create a mapper hook and to decode with a custom decoder

```golang
// Int64OrFloat64ToTimeDurationHookFunc returns a DecodeHookFunc that converts
// int64 or float64 to time.Time.
func ToTimeHookFunc() mapstructure.DecodeHookFunc {
	return func(
		f reflect.Type,
		t reflect.Type,
		data interface{}) (interface{}, error) {
		if t != reflect.TypeOf(time.Time{}) {
			return data, nil
		}

		switch f.Kind() {
		case reflect.String:
			return time.Parse(time.RFC3339, data.(string))
		case reflect.Float64:
			return time.Unix(0, int64(data.(float64))*int64(time.Millisecond)), nil
		case reflect.Int64:
			return time.Unix(0, data.(int64)*int64(time.Millisecond)), nil
		default:
			return data, nil
		}
		// Convert it by parsing
	}
}

func Decode(input map[string]interface{}, result interface{}) error {
	decoder, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		Metadata: nil,
		DecodeHook: mapstructure.ComposeDecodeHookFunc(
			ToTimeHookFunc()),
		Result: result,
	})
	if err != nil {
		return err
	}

	if err := decoder.Decode(input); err != nil {
		return err
	}
	return err
}
```

**Comment by mitchellh** [comment]
Thanks

**Comment by artking28** [comment]
Thank u so much, it works

**Comment by artking28** [comment]
> 

Thank u so much, it works
