### ISSUE TITLE
[QUESTION] map all unknown fields to some map

### ISSUE THREAD

**Issue by ghost** [mitchellh/mapstructure#162]
For example, I have structure like this:
```
type Test struct {
   Known string
   Unknown map[string]string
}
```
and yaml 
```
knonw: test
hello: world
john: snow
```
and I want to put keys `hello` and `john` to Unknown field. Is that possible?

**Comment by camdencheek** [comment]
`mapstructure.Metadata` can be added to the config to track unused fields. That can then be used to add those fields to your struct. 

Example: 
```
package main

import (
	"fmt"

	"github.com/mitchellh/mapstructure"
)

type TestStruct struct {
	Foo    string
	Unused map[string]interface{}
}

func main() {
	m := map[string]interface{}{
		"foo": "bar",
		"oof": "rab",
	}

	var res TestStruct
	meta := &mapstructure.Metadata{}
	config := &mapstructure.DecoderConfig{
		Metadata: meta,
		Result:   &res,
	}
	d, err := mapstructure.NewDecoder(config)
	if err != nil {
		panic(err)
	}

	err = d.Decode(m)
	if err != nil {
		panic(err)
	}

	res.Unused = make(map[string]interface{})
	for _, key := range meta.Unused {
		res.Unused[key] = m[key]
	}

	fmt.Printf("%#v\n", res)

}
```

Outputs: 
```
main.TestStruct{Foo:"bar", Unused:map[string]interface {}{"oof":"rab"}}
```

**Comment by camdencheek** [comment]
Per [the docs](https://godoc.org/github.com/mitchellh/mapstructure#hdr-Remainder_Values), you should also be able to use the struct tag `,remain`, but I wasn't able to get that to work.

**Comment by mitchellh** [comment]
Hey @camdencheek, this is a new feature that was is covered with a couple diff unit tests. Can you show the example? This should work and we should be able to close this out.

**Comment by camdencheek** [comment]
@mitchellh --  it looks I'd accidentally pinned an older version of `mapstructure` in that project. Everything worked fine once I pulled in the latest.

**Comment by mitchellh** [comment]
Great! Closing 😄
