### ISSUE TITLE
Unexpected ziphash?!

### ISSUE THREAD

**Issue by trtg** [mitchellh/mapstructure#163]
I am using go modules. Starting today i cannot compile a project that indirectly depends on this library because of this error:

go: extracting github.com/mitchellh/mapstructure v1.1.2
go: verifying github.com/mitchellh/mapstructure@v1.1.2: unexpected ziphash: ""

I've tried removing any reference to mapstructure from go.sum and removing mapstructure from $GOPATH/pkg/mod, both to no avail. Anyone have any idea how to fix this?

**Comment by mitchellh** [comment]
This sounds like an issue with Go or your environment. I work with a lot of projects daily that depend on this and have cleared my cache before and this has not been an issue. It has also been over 6 months with no other responses here so I'm guessing this is not hit by others or now resolved. Let me know if you still see it.

**Comment by zababurinsv** [comment]
I have same problem

go get -u github.com/go-delve/delve/cmd/dlv

verifying github.com/go-delve/delve@v1.6.1: unexpected ziphash: ""
