### ISSUE TITLE
Configure Boolean Conversion

### ISSUE THREAD

**Issue by dlpetrie** [mitchellh/mapstructure#169]
Is there a way to configure the boolean conversion? Our project has strict requirements to only accept a "true" and "false" and not all the other variations. Is this possible with this library?

**Comment by mitchellh** [comment]
Not without rolling your sleeves up a bit: you'd probably have to use a custom type and create a decode hook to do this manually. The weakly typed input mode accepts anything that Go's `ParseBool` supports which is much more generic.
