### ISSUE TITLE
Custom decoders?

### ISSUE THREAD

**Issue by hcliff** [mitchellh/mapstructure#17]
The json package providers a Unmarshaler interface that allows types to define how they should be decoded:

e.g: https://github.com/xushiwei/mgo/blob/master/src/labix.org/v2/mgo/bson/bson.go#L232

I'm looking to do something similar with mapstructure, what would be the best approach?

**Comment by mitchellh** [comment]
Use the DecodeHook functionality, which should be much improved now.
