### ISSUE TITLE
Inconsistent input

### ISSUE THREAD

**Issue by alex1891** [mitchellh/mapstructure#175]
Hi guys, 
i have a problem decoding data. The main problem is, that the type of the input values can change. For example:

```
{
   name: "hello",
   value: "abc"
}
```

and sometimes it looks like this:
```
{
   name: "hello",
   value:  
     payload: {
       otherdata: "dd",
       foo: "bar"
    }
}

```
Can I decode this with mapstructure? 

Best reguards
Alex

**Comment by mitchellh** [comment]
Not without writing a normalization layer yourself. Sorry!
