### ISSUE TITLE
Fail checksum

### ISSUE THREAD

**Issue by verzth** [mitchellh/mapstructure#181]
![image](https://user-images.githubusercontent.com/9104511/77055930-464baf00-6a04-11ea-8063-ee31c4e6eea9.png)

**Comment by dselyuzhitskiy** [comment]
Same problem

**Comment by Haufeng** [comment]
same problem

**Comment by euskadi31** [comment]
same problem

go version go1.14 darwin/amd64

```
verifying github.com/mitchellh/mapstructure@v1.2.0: checksum mismatch
	downloaded: h1:pFIkD+d/36DA4zE+VL2xI0Th1yNh+CWaUcJkaGivz3A=
	go.sum:     h1:kD6v71B7eGJ85s93kFx36uNn6BUAdTrcTtFbFLXqxFM=
```

**Comment by mitchellh** [comment]
Should be fixed now. Sorry, that was my mistake. I repushed a changelog change in 1.2.0 thinking the checksum was only across Go files. Whoops! 1.2.1 is out now.
