### ISSUE TITLE
Confusing decoding behavior if struct fields are not exported

### ISSUE THREAD

**Issue by yamil-rivera** [mitchellh/mapstructure#182]
If a struct has all fields private, the Decode() function will leave it empty because it's skipping unexported fields. I understand why exported fields are required but probably the function could return an error when all fields are like this instead of an empty struct. It could save some beginners like myself some debugging specially when we are consuming a consumer of your module, [viper](https://github.com/spf13/viper) in my case.

**Comment by camdencheek** [comment]
This seems to be the same behavior as `encoding/json`, and throwing an error when nothing was decoded is probably somewhat of an anti-pattern. 

Stdlib behavior:
```package main

import (
	"encoding/json"
	"fmt"
)

type TestStruct struct {
	foo string
}

func main() {
	j := `{"foo": "bar"}`
	var ts TestStruct
	err := json.Unmarshal([]byte(j), &ts)
	fmt.Printf("Struct: %#v\nErr: %#v\n", ts, err)
}
```

Outputs:
```
Struct: main.TestStruct{foo:""}
Err: <nil>
```

**Comment by yamil-rivera** [comment]
Thanks for the example! I did not know it was a known behavior in stdlib. I notices they had an (error type)[https://golang.org/src/encoding/json/decode.go?s=5839:5935#L133] regarding this problem but it's now deprecated. Do you think the problem could be explained in the documentation somewhere? Or is it a safe assumption to make due to the stdlib unmarshalling behavior?

**Comment by mitchellh** [comment]
I don't mind adding this to the docs.

I think the "safe assumption" comes from some level of Go experience. It isn't obvious up front I admit but eventually I think most Go developers learn that unexported fields can't be set by anything outside of the package it is defined (and `mapstructure` and `encoding/json` are outside of that package).

**Comment by yamil-rivera** [comment]
Opened [PR](https://github.com/mitchellh/mapstructure/pull/184)

**Comment by epolar** [comment]
Maybe we need func like `MarshaJSON` `UnmarshalJSON` for json.That we can map struct who has all fields private?
