### ISSUE TITLE
No support for anonymous structs 

### ISSUE THREAD

**Issue by cameront** [mitchellh/mapstructure#19]
Given a struct ("outer") that hosts an anonymous inner struct ("inner")...
```go
type inner struct {
  I1 string
}

type outer struct {
  inner
  O1 int
}
```
I expected mapstructure.Decode to take the following map:
```go
map[string]interface{}{
  "I1": "foo",
  "O1": 2
}
```
And populate outer.I1. I expected this mostly because I think of mapstructure.Decode and json.Unmarshal as analogous. json.Unmarshal does populate anonymous struct fields like this.

Was it intentional not to support anonymous structs?

**Comment by ryanuber** [comment]
@mitchellh I just ran into this one myself as well. Any pointers? Not sure how deep the reflection has to go to handle this gracefully. I think JSON somehow is doing it.

**Comment by mitchellh** [comment]
Looking into this now.

**Comment by mitchellh** [comment]
Ah, fixed with the example @ryanuber showed, I also pushed up fixes to make the tests pass 100% of the time.
