### ISSUE TITLE
time.Time encoded as map[string]interface{}{}

### ISSUE THREAD

**Issue by smyrman** [mitchellh/mapstructure#191]
Noticed that if encoding a struct into a map, `time.Time` entries are passed into empty maps, which doesn't seam very useful.

I could add a hook to encode it into a _string_ instance, but because hooks run as pre-processors, it's not possible to _preserve it_ as a time.Time.

Example code:
```go
package main

import (
	"fmt"
	"time"

	"github.com/mitchellh/mapstructure"
)

func PayloadEncoder(target *map[string]interface{}) (*mapstructure.Decoder, error) {
	return mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		//DecodeHook: mapstructure.ComposeDecodeHookFunc(
		// <- no hook can be added here to solve this.
		//),
		Result: target,
	})
}

type MyStruct struct {
	CreatedAt time.Time
}

func main() {
	p1 := MyStruct{
		CreatedAt: time.Now(),
	}
	m1 := make(map[string]interface{})
	d1, err := PayloadEncoder(&m1)
	fmt.Println("\nerr:", err, "\ndec:", d1, "\nmap:", m1)
	err2 := d1.Decode(p1)
	fmt.Printf("\nerr: %v\noutput: %#v\n", err2, m1)
}
```
Output:
```

err: <nil> 
dec: &{0xc0001be000} 
map: map[]

err: <nil>
output: map[string]interface {}{"CreatedAt":map[string]interface {}{}}
```

**Comment by Dragomir-Ivanov** [comment]
Hi @smyrman ,
Have you considered using "github.com/fatih/structs"?

https://play.golang.org/p/rFTAG5bcUI4

**Comment by mitchellh** [comment]
I believe #183 should address this.

**Comment by yjwong** [comment]
Hello @mitchellh, firstly, thanks for this library. I've been trying to achieve something similar, converting from a struct into a `map[string]interface{}` while preserving `time.Time` fields, but looking at the changes in #183, I wasn't entirely sure how to do it.

I tried setting a new `reflect.Value` to the `to` argument but it seems like we can't change the type of a `reflect.Value`.

Are there any examples/hints on how this can be achieved?

**Comment by smyrman** [comment]
Agree with @yjwong; I don't quite see _how_ #183 allows solving this problem.

The problem is that _after_ `DecodeHookExec` is run, then `mapstructure` would _still_ run through the "default" transitions, in which case it will find that it is converting a `time.Time` to an `interface{}` value, and convert it to an empty `map[string]interface{}`.

**Comment by mimol91** [comment]
Having this same issue

**Comment by MessageDream** [comment]
Having this same issue

**Comment by gatspy** [comment]
mark this issue

**Comment by johnny-oriente** [comment]
Same issue

**Comment by Dragomir-Ivanov** [comment]
@smyrman, Hi there! This new https://github.com/worldline-go/struct2 package may be of interest to you too.

**Comment by smyrman** [comment]
We have work-around this issue long ago by writing our own implementation of the struct / slice  -> map[string]interface{} / []interface{} conversion path, and using mapstructure for the to struct path only.

The struct2 `omitnested` struct tag might work as a way to fix the problem for others though.

**Comment by Dragomir-Ivanov** [comment]
@smyrman They are new kid on the block, so they might be willing to clean up. Their interface is not that big though, so renaming might be easy.
