### ISSUE TITLE
Allow override decode semantics through decode middleware

### ISSUE THREAD

**Issue by smyrman** [mitchellh/mapstructure#192]
As shown by #191 and #115, it is not possible through the current hook system to specify override semantics because hooks only does pre-processing.

To my experience, middleware is _always_ more powerful than hooks, because you can control the flow a lot better.

I think it would make sense to introduce a middleware for:
```go
func (d *Decoder) decode(name string, input interface{}, outVal reflect.Value) error
```

Example implementation stub:
```go
type DecodeFunc func(name string, input interface{}, outVal reflect.Value) error

type DecoderConfig struct{
   ...
   // if defined, pass in Decoder.decode to get a new DecodeFunc.
   // Fallback to call Decoder.decode directly.
   DecodeMiddleware func(DecodeFunc) DecodeFunc
}
```

With an example implementation for preserving `time.Time` as described in #191 (although this should probably be handled by default as well):
```go
func PreseveTimeMiddlware(next DecodeFunc) DecodeFunc {
    return func(name string, input interface{}, outVal reflect.Value) error {
        inVal := reflect.ValueOf(input)
        if _, ok := input.(time.Time); ok && inVal.Type(input).AssignableTo(outVal.Type()) {
            outVal.Set(inVal)
            return nil
        }
        return next(name, input, outVal)
    }
}
```

**Comment by smyrman** [comment]
PS! As for what to do with the existing hook types, and functions, they would still _work_, but it would make sense (to me) to document them as deprecated; they really just do half the job, and they add complexity...

**Comment by smyrman** [comment]
Implementation wise it's probably not _exactly_ as straight-farward as explained. The middleware must of-course run _recrusivly_ from the inner funciton, so the bit to replace, is probably the code here:
https://github.com/mitchellh/mapstructure/blob/14428cd8e72132155ec2f0f13c4eb93ffe620f7c/mapstructure.go#L423

Put the switch-case inside a new function, and pass it to the middlware func before calling.
The lower bit with the meta-data update must happen after.

**Comment by mitchellh** [comment]
Thanks for the suggestion. I believe everything you want to do would be possible by composing decode hooks using the new #183 PR (I saw you responded there as well). In general, I'm a fan of middleware, but the aforementioned PR fits the existing "shape" of this project so I wanted to give that a shot. Let me know if that doesn't solve things for you!
