### ISSUE TITLE
Ability to use encoding.TextUnmarshaler

### ISSUE THREAD

**Issue by j0hnwhyte** [mitchellh/mapstructure#204]
I think it would be nice to have the library support the standard `encoding.TextUnmarshaler` interfaces, so when it's about to unmarshal a string into a field (which may be of its own type), it actually instantiates that type and calls its `UnmarshalText()` method.

This way the object we're unmarshalling to implicitly declares how it can decode data. A use case? UUIDs stored through arrays instead of strings.

An example implementation:
```go
            fi := field.Interface()
_, canTextUnmarshal := fi.(encoding.TextUnmarshaler)
if canTextUnmarshal {
  t := field.Type().Elem()
  newValTyp := reflect.New(t)
  field.Set(newValTyp)

  unmarshaller, _ := field.Interface().(encoding.TextUnmarshaler)
  err := unmarshaller.UnmarshalText([]byte(v.(string)))
  if err != nil {
    panic(err)
  }
} else {
  newVal = reflect.ValueOf(v)
}
```

The standard go json decoder also implements this if I'm not mistaken.

Opinions?

**Comment by mitchellh** [comment]
I'd be open to a PR doing this. Thank you!
