### ISSUE TITLE
decodeInt throws an error for an empty string

### ISSUE THREAD

**Issue by elledoo** [mitchellh/mapstructure#206]
Hi!
Is it by design that decoding an empty string with ```decodeInt``` (```case dataKind == reflect.String && d.config.WeaklyTypedInput```) throws an error? There is no check for an empty string and ```strconv.ParseInt``` does indeed throw an error when an empty string is encountered. I would rather expect to be able to decode an empty string to 0 for WeaklyTypedInput

**Comment by mitchellh** [comment]
No, it should probably return 0 as you suggest.
