### ISSUE TITLE
Ability to match map keys case sensitively

### ISSUE THREAD

**Issue by mflorin** [mitchellh/mapstructure#208]
Hello,

I've came across a use case where the decoder should match map keys in a case sensitive manner (we were parsing some user input into some maps and then some structs).

I've created pull request #207 for this.

Please let me know if you think this would be useful and if you want this to be integrated into the next release.

Thank you,
Florin

**Comment by rpajak-solarwinds** [comment]
It makes a lot of sense if someone needs strict decoding. Then it makes sense e.g. to use it together with `ErrorUnused` config.

**Comment by mitchellh** [comment]
Fixed by #250
