### ISSUE TITLE
Library had method to decode but no have encode?

### ISSUE THREAD

**Issue by mghifariyusuf** [mitchellh/mapstructure#211]
We can use `mapstructure.Decode` to convert map to struct, but how to convert struct to map?
Why your library don't have method to encode?
Thankyou in advance

**Comment by mitchellh** [comment]
Reverse the arguments

**Comment by mghifariyusuf** [comment]
I reverse the arguments and got error `reflect: call of reflect.Value.Interface on zero Value`
because my struct have nil field, like this:
```
x := Struct {
   A: "xxxx",
   B: nil,
}
```

**Comment by mitchellh** [comment]
Might be a bug, can you please open a new issue with the input/output you're trying to do and I'll take a look!

**Comment by mghifariyusuf** [comment]
Ok here https://github.com/mitchellh/mapstructure/issues/212
