### ISSUE TITLE
mapstructure.Decode doesn't empty a list with multiple values

### ISSUE THREAD

**Issue by alonyb** [mitchellh/mapstructure#214]
In a loop(for) I was decoding a firestore map into a struct. I've a list of arrays inside struct so when I decode map interface into struct it doesn't empty the older list, it append to the new list in struct.

Temporary Solution:

- Set struct to nil in every loop run

Example:

```
var out model
for i, data := range dataMap {
   err = mapstructure.Decode(data, &model)
}
```

Solution
```
var out model
for i, data := range dataMap {
   a := &model
   a.Data.Services= nil
   err = mapstructure.Decode(data, &model)
}
```

**Comment by mitchellh** [comment]
Yes, this is by design. You have to set the `ZeroFields` config to true if you want this behavior. I hope that helps!

**Comment by mitchellh** [comment]
I suppose it helps to say why this is by design: folks were decoding and building up configs from multiple sources and wanted this behavior.
