### ISSUE TITLE
Not working with underscores

### ISSUE THREAD

**Issue by metehus** [mitchellh/mapstructure#219]
I found out a problem when dealing with underscores. Take a look at this code:

```go
package main

import (
	"encoding/json"
	"fmt"
	"github.com/mitchellh/mapstructure"
)

type TestStruct struct {
	Foo       interface{} `json:"foo"`
	TestValue string      `json:"test_value"`
}

type InsideStruct struct {
	Something     string `json:"something"`
	SomethingElse string `json:"something_else"`
}

func main() {
	strg := "{\"foo\": {\"something\": \"123\", \"something_else\": \"hello world\"}, \"test_value\": \"test\"}"
	
	var decoded TestStruct
	json.Unmarshal([]byte(strg), &decoded)
	
	var insideData InsideStruct

	mapstructure.Decode(decoded.Foo, &insideData)

	fmt.Println(strg)
	fmt.Println(decoded)
	fmt.Println(insideData)
}

```

*[playground](https://play.golang.org/p/u1cZgno-Sc_M)*

The result of the following code is:
```
{"foo": {"something": "123", "something_else": "hello world"}, "test_value": "test"}
{map[something:123 something_else:hello world] test}
{123 }
```

You can see that the `something_else` variable is not decoded to the `insideData` variable.

**Comment by mitchellh** [comment]
You have to use the `mapstructure` tag (not "json") or use a DecoderConfig to set the tag to "json"

**Comment by metehus** [comment]
Ok, nervermind. I just looked at examples and found out that using `mapstructure` instead of `json` works:

```go
type InsideStruct struct {
	Something     string `json:"something"`
	SomethingElse string `mapstructure:"something_else"`
}
```

*[playground](https://play.golang.org/p/DGvhzs9ltwR)*

**Comment by metehus** [comment]
> You have to use the `mapstructure` tag (not "json") or use a DecoderConfig to set the tag to "json"

Just looked at that. Thanks!
