### ISSUE TITLE
Squash embedded struct only for one type, it gives me error

### ISSUE THREAD

**Issue by frederikhors** [mitchellh/mapstructure#220]
First of all a very huge thanks for your work! It's amazing!

### Reproduction

https://play.golang.org/p/Wl0BuyUYC33

I do not understand why I'm getting this error:

`error="1 error(s) decoding:\n\n* '' has invalid keys: id"`

I have:

```go
type BaseModel struct {
	ID        int
	CreatedAt time.Time
}

type OrderRow struct {
	BaseModel

	Amount int
}
```

I'm trying to decode this map:

```go
orderRow := map[string]interface{}{
  "id": 123,
  "amount": 456,
}
```

to a new `OrderRow` struct using the code from https://gqlgen.com/reference/changesets/:

```go
func ApplyChanges(changes map[string]interface{}, to interface{}) error {
	dec, err := mapstructure.NewDecoder(&mapstructure.DecoderConfig{
		ErrorUnused: true,
		TagName:     "json",
		Result:      to,
		ZeroFields:  true,
		// This is needed to get mapstructure to call the gqlgen unmarshaler func for custom scalars (eg Date)
		DecodeHook: func(a reflect.Type, b reflect.Type, v interface{}) (interface{}, error) {
			if reflect.PtrTo(b).Implements(reflect.TypeOf((*graphql.Unmarshaler)(nil)).Elem()) {
				resultType := reflect.New(b)
				result := resultType.MethodByName("UnmarshalGQL").Call([]reflect.Value{reflect.ValueOf(v)})
				err, _ := result[0].Interface().(error)
				return resultType.Elem().Interface(), err
			}

			return v, nil
		},
	})

	if err != nil {
		return err
	}

	return dec.Decode(changes)
}
```

**If I add `Squash: true,` to `DecoderConfig` it works.**

But if I wanna use `Squash` only on this type it gives me that error.

I tried this:

```go
type BaseModel struct {
	ID        int `mapstructure:",squash"`
	CreatedAt time.Time
}

type OrderRow struct {
	BaseModel `mapstructure:",squash"`

	Amount int
}
```

but it doesn't work.

Can you help me figure out where I'm wrong?

**Comment by frederikhors** [comment]
Added reproduction with Go Playground.

**Comment by uvw** [comment]
I am not the author of this cool library but since you mentioned me 😅: 

The issue is that you set the tag name used by mapstructure to `json:` in the `DecoderConfig` but specified `mapstructure:` in the struct fields. If you change the struct tags to `json:`, your code will work (https://play.golang.org/p/jsCVQ3u4VPe, check the output).

**Comment by mitchellh** [comment]
Thanks @uvw
