### ISSUE TITLE
mapstructure.Decode() works incorrect!

### ISSUE THREAD

**Issue by shuhrat-shokirov** [mitchellh/mapstructure#223]
First of all, thanks for this great package. I'm having a problem with decoding a structure.
Example:
```
input = type Lang struct {
	Ru string `json:"ru-RU" mapstructure:"ru"`
	Tj string `json:"tj-TJ" mapstructure:"ta"`
	En string `json:"en-EN" mapstructure:"en"`
	Uz string `json:"uz-UZ" mapstructure:"uz"`
}
```

By sample input above I'm waiting to get the result below.
```
output = type Language struct {
	RU string `json:"ru"`
	TJ string `json:"ta"`
	UZ string `json:"uz"`
	EN string `json:"en"`
}
```

But the problem here I'm getting an empty field in the second line: ```"ta"```.

![изображение](https://user-images.githubusercontent.com/25120373/102466410-d0e33c80-4070-11eb-914c-ef75bdaa1794.png)
![изображение](https://user-images.githubusercontent.com/25120373/102466498-e9ebed80-4070-11eb-87e7-386a79307cbe.png)

Another problem I'm facing here it's when I turn the second line in input to "tj" it's work in a weird way for me and give me in the out result with "ta" as shown below. 
```
input = type Lang struct {
	Ru string `json:"ru-RU" mapstructure:"ru"`
	Tj string `json:"tj-TJ" mapstructure:"tj"`
	En string `json:"en-EN" mapstructure:"en"`
	Uz string `json:"uz-UZ" mapstructure:"uz"`
}
```
```

output = type Language struct {
	RU string `json:"ru"`
	TJ string `json:"ta"`
	UZ string `json:"uz"`
	EN string `json:"en"`
}
```

![изображение](https://user-images.githubusercontent.com/25120373/102466810-5666ec80-4071-11eb-9e36-f9137a7ffceb.png)
![изображение](https://user-images.githubusercontent.com/25120373/102466834-5e269100-4071-11eb-9734-167fcebf92d2.png)

**Comment by mitchellh** [comment]
You must set the `mapstructure` tags on the output as well.
