### ISSUE TITLE
Empty key name when decoding map from struct with only omitempty flag

### ISSUE THREAD

**Issue by semrekkers** [mitchellh/mapstructure#238]
If a structtag only contains `,omitempty` when decoding a map from a struct, the keyName is overwritten by an empty string. I can't find whether this is defined behavior. If not, I have a PR ready to fix this.

Example:
```go
type Struct struct {
	Username string `mapstructure:",omitempty"`
}

s := Struct{
	Username: "Joe",
}
var m map[string]interface{}
mapstructure.Decode(s, &m)

// Output: map[:Joe]
// Expected output: map[Username:Joe]
fmt.Printf("%+v", m)
```

**Comment by mitchellh** [comment]
Definitely a bug, I pulled in your test and modified it slightly. Thank you!
