### ISSUE TITLE
Override only NON nil values of Struct

### ISSUE THREAD

**Issue by jnvillar** [mitchellh/mapstructure#242]
I would like to use this awesome lib to set default values os some struct. For example given the following args

```
type MyStruct {
	Name *string  // name can be nil
}

var defaultValues = map[string]interface{}{
	"name" : "default_name" 
}
```

I would like that 

``` 
noNameSet:= &MyStruct{}
nameSet := &MyStruct{Name: "some_name"}

mapstructure.Decode(defaultValues, &noNameSet)

mapstructure.Decode(defaultValues, &nameSet)


// this prints default_name
fmt.Println(noNameSet.Name)

// this prints some_name
fmt.Println(nameSet.Name)

```

I understand that this is not possible now (mapstructure.Decode always overrides the values of the struct)

It would be a great feature for setting default values of a given struct.

**Comment by mitchellh** [comment]
I recommend using this library alongside `mergo` or some equivalent. That is far better suited for defaults than this library.
