### ISSUE TITLE
Slice *Struct hold time.Time to Slice *Struct hold *time.Time

### ISSUE THREAD

**Issue by NuVivo314** [mitchellh/mapstructure#260]
Hello,

I can't convert : 
```golang
	type TimeTimeValue struct {
		T *struct {
			TimePtrForVal time.Time
			TimePtr       *time.Time
		}
	}
```
to
```golang
	type TimeTimePtr struct {
		T *struct {
			TimePtrForVal *time.Time
			TimePtr       *time.Time
		}
	}
```

`TimeTimePtr.T.TimePtrForVal ` is empty.

The hook throw panic if replace `map[string]interface` to `*time.Time`

**Comment by NuVivo314** [comment]
I still come with a solution,
NuVivo314/mapstructure@3f1721a4f7b5ad10107b7e523f6d3b132ccac2ab

I do a pull request if it is possible

**Comment by NuVivo314** [comment]
Ok, i'm find solution via Hook. I don't know if my PR is "library spirit" 

Hook solution like: 
```golang
	uniqueSearch := reflect.ValueOf(fmt.Sprint(rand.Uint64()))
	typeTime := reflect.TypeOf(&time.Time{})
	return func(from reflect.Value, to reflect.Value) (interface{}, error) {
		if from.Type() == typeTime && to.Kind() == reflect.Map {
			to.SetMapIndex(uniqueSearch, from)
			return to.Interface(), nil
		}
		if to.Type() == typeTime && from.Kind() == reflect.Map {
			v := from.MapIndex(uniqueSearch)
			if v.IsNil() {
				return nil, nil
			}
			if !v.CanAddr() && v.Elem().CanConvert(typeTime) {
				return v.Elem().Interface(), nil
			}

			return v.Interface(), nil
		}
		return from.Interface(), nil
	}
```

**Comment by mitchellh** [comment]
I think using a hook is correct here. If I recall, `time.Time` has unexported fields so we can't properly recreate it into a pointer. I think! The hook workaround is good. If someone can generalize this to structs and show a bug/fix for that, I'd merge it.
