### ISSUE TITLE
Renaming fields via json: directive

### ISSUE THREAD

**Issue by ITler** [mitchellh/mapstructure#268]
Hello. First thank you for providing this library. It is very helpful.

I would like to propose the following:
To reduce repitition in code when it comes to [mapping field names](https://github.com/mitchellh/mapstructure/blob/master/mapstructure.go#L27-L35) maybe changing from 

    `mapstructure: "alternativeFieldname"` 

to 

    `json: "alternativeFieldname"`

would be useful, as I think the `json: ` directive would be used and defined on the struct anyways. Kind of relates to: #256

What do you think?

**Comment by Necoro** [comment]
You can set the tag name to use in your `DecoderConfig` if you want something like this. For example, I reuse `yaml`-tags.
Isn't this sufficient?

**Comment by ITler** [comment]
Argh, I am blind. Of cause this is sufficient. Thanks for replying.
