### ISSUE TITLE
Support Decode time.Time into string

### ISSUE THREAD

**Issue by iorip** [mitchellh/mapstructure#270]
For struct like:

```go
type Model struct {
	CreatedAt time.Time  `xorm:"created index" json:"created_at" mapstructure:"created_at"`
	UpdatedAt time.Time  `xorm:"updated index" json:"updated_at" mapstructure:"updated_at"`
	DeletedAt *time.Time `xorm:"deleted" json:"deleted_at,omitempty" csv:"-" mapstructure:"deleted_at,omitempty"`
}
```
Attempt to convert from struct to map:

```go
t := time.Now()
in := Model{
    CreatedAt: t,
    UpdatedAt: t,
}
var out map[string]interface{}
err := mapstructure.Decode(&in, &out)
if err != nil {
    panic(err)
}
```

Got:

```json
{
  "created_at": {},
  "updated_at": {}
}
```

Expect: (like built-in encoding/json)

```json
{
  "created_at": "2022-01-20T14:07:45.875297+08:00",
  "updated_at": "2022-01-20T14:07:45.875297+08:00"
}
```

**Comment by leopku** [comment]
same issue

**Comment by mabezdek** [comment]
some issue

**Comment by AnkoGo123** [comment]
> For struct like:
> 
> ```go
> type Model struct {
> 	CreatedAt time.Time  `xorm:"created index" json:"created_at" mapstructure:"created_at"`
> 	UpdatedAt time.Time  `xorm:"updated index" json:"updated_at" mapstructure:"updated_at"`
> 	DeletedAt *time.Time `xorm:"deleted" json:"deleted_at,omitempty" csv:"-" mapstructure:"deleted_at,omitempty"`
> }
> ```
> 
> Attempt to convert from struct to map:
> 
> ```go
> t := time.Now()
> in := Model{
>     CreatedAt: t,
>     UpdatedAt: t,
> }
> var out map[string]interface{}
> err := mapstructure.Decode(&in, &out)
> if err != nil {
>     panic(err)
> }
> ```
> 
> Got:
> 
> ```json
> {
>   "created_at": {},
>   "updated_at": {}
> }
> ```
> 
> Expect: (like built-in encoding/json)
> 
> ```json
> {
>   "created_at": "2022-01-20T14:07:45.875297+08:00",
>   "updated_at": "2022-01-20T14:07:45.875297+08:00"
> }
> ```

look at "github.com/fatih/structs",but not surport Unmarshal by using the "mapstructure".

**Comment by AnkoGo123** [comment]
i fix it 👍 
look this https://blog.csdn.net/u010570551/article/details/105193144

**Comment by mitchellh** [comment]
Use a decode hook function for this, this is what they're for. We didn't include automatic time decoding because there are a lot of formats we could decode to. If someone wants to write a `TimeToStringDecodeHook` I'd be happy to include that alongside the project (since we already have `StringToTime`).
