### ISSUE TITLE
raise an error if mandatory field is missing, opposite logic to ErrorUnused

### ISSUE THREAD

**Issue by avoidik** [mitchellh/mapstructure#275]
hi,

is there a way to raise an error if there was no corresponding value defined in the source map?

with `ErrorUnused` set in `DecoderConfig` the code below should raise an error:

```
# source
map[string]interface{}{
    "name": "john",
    "surname": "doe",
    "hobby": "books",
}
```

```
# dest
type UserInfo struct {
	Name     string `mapstructure:"name"`
	Surname string `mapstructure:"surname"`
}
```

I am looking for something like `ErrorUnbound`, for example the code below should raise an error if `surname` is missing

```
# source
map[string]interface{}{
    "name": "john",
    "hobby": "books",
}
```

```
# dest
type UserInfo struct {
	Name     string `mapstructure:"name"`
	Surname string `mapstructure:"surname"`
}
```

**Comment by mitchellh** [comment]
Master (and soon to be 1.5.0) contains `ErrorUnset` which is probably what you're looking for. For richer validation, I recommend a full validation library like ozzo-validation or go-playground/validator.
