### ISSUE TITLE
Handle time.Time?

### ISSUE THREAD

**Issue by clarktlaugh** [mitchellh/mapstructure#29]
I have a structure like this:

`type TestEntry struct {
        Id string         `json:"id" mapstructure:"id"`
        MemberId string
        Present bool
        Date time.Time
        Type string
}`

And a map[string]interface{} like this that I am trying to map to the structure:

`map[string]interface {}{"Present":true, "Type":"Other", "id":"342358db-4e66-4e39-a452-75859097bc39", "Date":time.Time{sec:63566170074, nsec:619999885, loc:(*time.Location)(0xc208030840)}, "MemberId":"81b3d896-4314-4078-aa00-a27782bc00b4"}`

When I try to decode, I get the following error:
* 'Date' expected a map, got 'struct'

Any suggestions?

**Comment by hectorj** [comment]
With pull request #31 and #32 this become possible

**Comment by mitchellh** [comment]
Thanks to @hectorj this now works!
