### ISSUE TITLE
How to decode the map with key containing hyphen (-) ?

### ISSUE THREAD

**Issue by monemo12** [mitchellh/mapstructure#296]
This is a source object, one of the field with a key containing hyphen (-)

```go
testEvt := map[string]interface{}{
    "detail-type": "TestEvent",
}
```

And my structure definition:

```go
type Event struct {
    DetailType string `filed:"required",mapstrcuture:"detail-type,omitempty",json:"detail-type"`
}
```

I tried to use `mapstructure.Decode` to convert the object into my structure, but it seems not working.

```go
var evt Event
m.Decode(testEvt, &evt)
log.Printf("| TestDecode: evt=%+v\n", evt)

// Output
// 2022/07/14 11:22:54 | TestDecode: evt={DetailType:}
```

**Comment by lkendrickd** [comment]
This works fine for me.  You also have a misspelling on your mapstructure tag.

```
	testEvt := map[string]interface{}{
		"detail-type": "TestEvent",
	}

	type Event struct {
		DetailType string `mapstructure:"detail-type"`
	}

	var evt Event
	ms.Decode(testEvt, &evt)
	log.Printf("| TestDecode: evt=%+v\n", evt)
```

**Comment by monemo12** [comment]
@lkendrickd 

It seems working fine if `DetailType` only with `mapstrcuture` tags, but when combining the `json` tag, then `mapstructure` is not working. Maybe I should avoid combine to use both `mapstrcuture` and `json` tag at the same time. Here my testing cases:

**1. Only with `mapstructure` tags**

**Source**
```go
testEvt := map[string]interface{}{
    "detail-type": "TestEvent",
}

type Event struct {
    DetailType string `mapstructure:"detail-type,omitempty",field:required`
}

var evt Event
m.Decode(testEvt, &evt)

log.Printf("| TestDecode: evt=%+v\n", evt)
```
**Output**
```sh
> 2022/09/21 09:45:09 | TestDecode: evt={DetailType:TestEvent}
```

---

**2. `mapstructure` tags + `json` tag**

**Source**
```go
testEvt := map[string]interface{}{
    "detail-type": "TestEvent",
}

type Event struct {
    DetailType string `json:"detail-type",mapstructure:"detail-type,omitempty",field:required`
}

(...ignore)
```

**Output**
```sh
> 2022/09/21 09:48:11 | TestDecode: evt={DetailType:}
```

**Comment by vaguecoder** [comment]
@monemo12 Not a mapstructure bug. The tag syntax is incorrect. There `shouldn't be commas between different tags`.
```go
type Event struct {
    DetailType string `json:"detail-type" mapstructure:"detail-type,omitempty" field:required`
}
```

**Comment by monemo12** [comment]
@vaguecoder Thanks for your information. It's working. I close this issue.
