### ISSUE TITLE
Support paths in the mapstructure name tag

### ISSUE THREAD

**Issue by bugreport0** [mitchellh/mapstructure#35]
When dealing with convoluted JSON hierarchies, I'd love to be able to write something like
```
type MyType struct {
 Field1 string `mapstructure:"/path/to/some/data/i/want"`
 Field2 int    `mapstructure:"/path/to/other/data/i/care/about"`
 Field3 []struct{
  Field4 float64 `mapstructure:"/support/for/nested/constructions"`
  ...
 } `mapstructure:"/would/be/nice/too"`
}
```
rather than typecast my way through all those `map[string]interfaces{}`, or define a bazillion intermediate types.

I think this can be implemented in a backwards-compatible way as well, since you can just check if the first character of the `mapstructure` tag is a legal Go identifier character, and if not, interpret the tag as a path (up to the first comma, to support attributes like `squash`). Said first character can then be used as the component separator, giving the design some extra flexibility. (Of course, I'm making the assumption here that most end-users of the package have `mapstructure` names that don't begin with special characters - those that do need to change their code so that the tag begins with a unique special character, to simulate a single-element path.)

**Comment by mitchellh** [comment]
I'd be open to looking at a PR for this. Otherwise, I think this might be an idea that should live higher level in another library (given some `map[string]interface{}` and  a query, extract the right value).
