### ISSUE TITLE
Minor issue in docs/signature of Decode.

### ISSUE THREAD

**Issue by shurcooL** [mitchellh/mapstructure#36]
There is an issue in [mapstructure.go#L108-L109](https://github.com/mitchellh/mapstructure/blob/2caf8efc93669b6c43e0441cdc6aed17546c96f3/mapstructure.go#L108-L109). The documentation states:

> val must be a pointer to a struct.

However, the signature has no parameter `val`:

``` Go
func Decode(m interface{}, rawVal interface{}) error {
```

I am guessing `val` should be changed to `rawVal` in documentation, or `rawVal` should be changed to `val` in the func signature. I'm not sure which direction is better, but the discrepancy should be resolved.

**Comment by shurcooL** [comment]
On a separate note, may I say I personally find the two variable names very hard to read... I keep having to look at the example usage to figure out which of the two is the input, an which is the output.

I would suggest using the variable names as done in the standard library for various encoding packages (e.g., [here](https://godoc.org/encoding/json#Unmarshal) and [here](https://godoc.org/encoding/xml#Unmarshal):

```Go
Decode(data interface{}, v interface{})
```

Where `data` is the input being decoded, and `v` is the pointer to a struct where it gets decoded. What do you think?

**Comment by shurcooL** [comment]
Any plans to fix this? It should be easy if there's an agreed plan to resolve this. Will you accept a PR?

**Comment by shurcooL** [comment]
Friendly ping.

If there's no interest in resolving this issue, I can close this issue.

**Comment by mitchellh** [comment]
Good feedback sorry it took 3 years (!!!) to address. :) Please see the associated commit. I think I addressed everything!

**Comment by shurcooL** [comment]
Yeah, it's been a while, but I never gave up hope! ;) Thanks for fixing it.

There might be a minor nit on that commit, see [my comment](https://github.com/mitchellh/mapstructure/commit/4a44588c25f82682ff55793e558d060b0056632e#r27337253). But otherwise the issue is indeed resolved.
