### ISSUE TITLE
Is performance a goal of this package or not?

### ISSUE THREAD

**Issue by shurcooL** [mitchellh/mapstructure#37]
Hi, a question about the objective of this package.

I understand it deals primarily with converting input of type `map[string]interface{}` (which you typically get as a result of unmarshalling JSON into `interface{}` because you don't know its concrete type in advance) to native Go structs.

However, beyond that, is performance a priority? Or is performance secondary to convenience of use (e.g., to make the user code simpler/shorter) or flexibility of input/output (e.g., mapstructure can unmarshal input of type `map[interface{}]interface{}`)?

The reason I ask is because it doesn't seem very fast compared to a very dumb brute-force alternative implementation: to marshal the input as some format (JSON, gob, XML, etc.) and decode it into target Go struct. For example:

```Go
// DecodeViaJSON takes the map data and passes it through encoding/json to convert it into the
// given Go native structure pointed to by v. v must be a pointer to a struct.
func DecodeViaJSON(data interface{}, v interface{}) error {
	// Perform the task by simply marshalling the input into JSON, then unmarshalling
	// it into target native Go struct.
	b, err := json.Marshal(data)
	if err != nil {
		return err
	}
	return json.Unmarshal(b, v)
}
```

I've written a benchmark to compare it against `mapstructure.Decode`:

```Go
// Original benchmark that uses mapstructure.Decode.
func Benchmark_Decode(b *testing.B) {
	type Person struct {
		Name   string
		Age    int
		Emails []string
		Extra  map[string]string
	}

	input := map[string]interface{}{
		"name":   "Mitchell",
		"age":    91,
		"emails": []string{"one", "two", "three"},
		"extra": map[string]string{
			"twitter": "mitchellh",
		},
	}

	var result Person
	for i := 0; i < b.N; i++ {
		Decode(input, &result)
	}
}

// My benchmark that uses DecodeViaJSON with same input as above.
func Benchmark_DecodeViaJSON(b *testing.B) {
	type Person struct {
		Name   string
		Age    int
		Emails []string
		Extra  map[string]string
	}

	input := map[string]interface{}{
		"name":   "Mitchell",
		"age":    91,
		"emails": []string{"one", "two", "three"},
		"extra": map[string]string{
			"twitter": "mitchellh",
		},
	}

	var result Person
	for i := 0; i < b.N; i++ {
		DecodeViaJSON(input, &result)
	}
}
```

Here are the results:

```
Benchmark_Decode		  100000	     18507 ns/op	    2773 B/op	      73 allocs/op
Benchmark_DecodeViaJSON	  100000	     14292 ns/op	    1466 B/op	      43 allocs/op
```

Counterintuitively, the seemingly dumb approach of just marshalling input into JSON bytes and decoding it from those bytes is actually both 29.5% **faster** and causes less memory allocations. /cc @gbbr

Do you have thoughts on this? Is this finding expected or unexpected?

(I understand this DecodeViaJSON will not work on all inputs that mapstructure.Decode currently supports, but it will work for all basic use cases.)

**Comment by mitchellh** [comment]
I'm sure there are improvements that can be made (and I'd love the benchmark as a PR!), but with anything with this much reflection, performance isn't an immediate priority. However, if we can make improvements I'd love to make them.

Please PR the benchmark! It'll give us a great starting point.
