### ISSUE TITLE
Accept string to time.Time as weak input

### ISSUE THREAD

**Issue by mantenie** [mitchellh/mapstructure#41]
It would be nice if the import can handle strings with a timestamp or a date time format as string.
Something like that: "2015-09-30T01:18:56.096224525+02:00"

**Comment by 17twenty** [comment]
Within two hours of the previous guy I am also looking for an RFC3339 string->time.Time

I saw some old issues/requests on similar - did it get nixed for a reason?

**Comment by 17twenty** [comment]
I ended up half-bodging your library to perform this - would be good to know how it could be plugged in but this is a snippet of what I've done (not pretty at the moment but wanted to share):

```
if f.Type().AssignableTo(reflect.ValueOf(time.Time{}).Type()) {
	tmp, ok := dataMap[elmentVal.Type().Field(i).Name].(string)
	if tmp2, err := time.Parse(time.RFC3339, tmp); err == nil && ok {
		l := reflect.ValueOf(tmp2)
		f.Set(l)
	}
}
```

I'm using this as part of a function to dynamically build structures and date/time is one of the issues in working with JSON as the base type.

**Comment by mantenie** [comment]
I solved it in my use case with that callback function:
```
stringToDateTimeHook := func(
		f reflect.Type,
		t reflect.Type,
		data interface{}) (interface{}, error) {
		if t == reflect.TypeOf(time.Time{}) && f == reflect.TypeOf("") {
			return time.Parse(time.RFC3339, data.(string))
		}

		return data, nil
	}
```

**Comment by 17twenty** [comment]
Do you have an example of where I can plug the hook in?

**Comment by mantenie** [comment]
I used this in a function:
````
config := mapstructure.DecoderConfig{
	DecodeHook: stringToDateTimeHook,
	Result:     &target,
}

decoder, err := mapstructure.NewDecoder(&config)
if err != nil {
	return nil, err
}

err = decoder.Decode(sourceMap)
if err != nil {
	return nil, err
}

**Comment by 17twenty** [comment]
Hey that worked pretty well - thanks Stefan.

I didn't quite get it from the docs so that was great. Be nice if there was
a way to try and dynamically cast from a string to other types but that
works as a substitute.

**Comment by evillemez** [comment]
Thank you both so much for the discussion here.  This saved me when I was trying to decode a custom Timestamp type that comes in as a string.  I shudder to think how much time I could have lost had I not come across this. :)

**Comment by mitchellh** [comment]
I hope this comes up in google and I would prefer this to be the way. Weak typing is an approach to weakly convert primitive types that you would intuitively expect to work that way (jokingly called PHP mode over here). I'm not sure if you'd intuitively expect a string to time to be RFC3339. It feels like that function would have to be significantly more complex to magically do the right thing.

What I'd be open to _instead_ is starting to build a sub-directory (subpackage) of mapstructure that contains common decoder hooks so that folks can find a "RFC3339ToTime" hook example.

**Comment by weitzj** [comment]
In case anybody else wants to have some kind of generic Decoder, which handles the date parsing in a sane way

```Go

import (
     "github.com/araddon/dateparse"
)


// ParseTime will parse an arbitrary date string and try to create a time.Time.
func ParseTime(date string) (time.Time, error) {
	if strings.TrimSpace(date) == "" {
		return time.Unix(0, 0), nil
	}
	return dateparse.ParseAny(date)
}

func Decode[T YOUR_INPUT_STRUCT_1 | YOUR_INPUT_STRUCT_2](input interface{}) (*T, error) {
	var out T
	config := mapstructure.DecoderConfig{
		DecodeHook: func(
			f reflect.Type,
			t reflect.Type,
			data interface{}) (interface{}, error) {
			if t == reflect.TypeOf(time.Time{}) && f == reflect.TypeOf("") {
				return ParseTime(data.(string))
			}

			return data, nil
		},
		Result: &out,
	}

	decoder, err := mapstructure.NewDecoder(&config)
	if err != nil {
		return nil, fmt.Errorf("creating decoder failed with error %w", err)
	}
	if err := decoder.Decode(input); err != nil {
		return nil, fmt.Errorf("decoding failed with error %w", err)
	}
	return &out, nil
}
```
