### ISSUE TITLE
Squash embedded structs by default

### ISSUE THREAD

**Issue by dtolnay** [mitchellh/mapstructure#42]
To be consistent with "encoding/json", an embedded struct like

```
type Outer struct {
    Inner
}
```

should behave as though tagged with `mapstructure:",squash"`, unless explicitly given a name like `mapstructure:"Inner"`.

Example code demonstrating the inconsistency with "encoding/json":

```
package main

import (
    "encoding/json"
    "fmt"
    "github.com/mitchellh/mapstructure"
)

type Inner struct {
    Name string
}

type Outer struct {
    Inner // works if you add `mapstructure:",squash"`
}

func main() {
    input := Outer{Inner: Inner{Name: "mitchellh"}}
    fmt.Printf("input: %#v\n", input)

    bytes, err := json.Marshal(input)
    if err != nil { panic(err) }
    fmt.Printf("json: %v\n", string(bytes))

    var outputGood Outer
    err = json.Unmarshal(bytes, &outputGood)
    if err != nil { panic(err) }
    fmt.Printf("outputGood: %#v\n", outputGood)

    var tmp interface{}
    err = json.Unmarshal(bytes, &tmp)
    if err != nil { panic(err) }
    fmt.Printf("tmp: %#v\n", tmp)

    var outputBad Outer
    err = mapstructure.Decode(tmp, &outputBad)
    if err != nil { panic(err) }
    fmt.Printf("outputBad: %#v\n", outputBad)
}
```

The output is:

```
input: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
json: {"Name":"mitchellh"}
outputGood: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
tmp: map[string]interface {}{"Name":"mitchellh"}
outputBad: main.Outer{Inner:main.Inner{Name:""}}
```

The correct output would have:

```
outputBad: main.Outer{Inner:main.Inner{Name:"mitchellh"}}
```

**Comment by bminer** [comment]
Maybe a configuration option could be passed to `NewDecoder` to squash by default?  That way, it doesn't need to be set on a tag in a struct for every embedded field.  Thoughts?

**Comment by reefbarman** [comment]
some way to specify the default squash behaviour would be appreciated and setting it as config option I believe is a suitable solution. This would help us reduce a bit of boiler plate in our code

**Comment by bminer** [comment]
This issue is too old.  I'm making a PR for this.  Also, "squash" is nowhere in the godoc.  Quoting a popular Netflix kids TV show, "It's time to be a hero!"

**Comment by Niondir** [comment]
Any updates here? Thanks for pointing out the squash tag :)
