### ISSUE TITLE
No encoding ?

### ISSUE THREAD

**Issue by n00dl3** [mitchellh/mapstructure#53]
> mapstructure is a Go library for decoding generic map values to structures and vice versa

At first glance, there is no way to encode a struct to a map with this library ..?

**Comment by silasdavis** [comment]
I was also looking for this. Something like https://github.com/fatih/structs will allow this. But it feels like Encode method belongs here as the dual of Decode.

**Comment by mitchellh** [comment]
This is funny because Encoding exists by just reversing the arguments to Decode. :) An Encode is just a decode of the opposite direction. So... that should work!

**Comment by n00dl3** [comment]
@mitchellh could you elaborate a bit more, please...

**Comment by mitchellh** [comment]
Oh whoops I thought we added struct support to the from value. That may be a simple fix because I think it is in there but will reopen until I take a look.

**Comment by silasdavis** [comment]
Any idea about whether you intend to take a look at this? If not I might take a look.

**Comment by mcos** [comment]
I opened #77 earlier to hopefully fix this issue.

**Comment by mcandre** [comment]
> This is funny because Encoding exists by just reversing the arguments to Decode. :) An Encode is just a decode of the opposite direction. So... that should work!

Could the API please provide an `Encode` convenience method, to make this more clear?
