### ISSUE TITLE
Allow anonymous non struct fields

### ISSUE THREAD

**Issue by emilevauge** [mitchellh/mapstructure#56]
Hi!
I'm facing an issue on traefik https://github.com/containous/traefik/issues/743 that prevents us from using an anonymous slice field in a struct:

```go
type Users []string

type Basic struct {
	Users `mapstructure:","` // explicitly don't squash 
}
```

Calling `Decode()` on `Basic` will produce the error `Users: unsupported type: slice`.
This behavior is due to the test https://github.com/mitchellh/mapstructure/blob/a6ef2f080c66d0a2e94e97cf74f80f772855da63/mapstructure.go#L654 which I'm not sure is needed as few lines later you have https://github.com/mitchellh/mapstructure/blob/a6ef2f080c66d0a2e94e97cf74f80f772855da63/mapstructure.go#L673.

Commenting the first test fixes my issue.
What are your thoughts on this?

**Comment by mitchellh** [comment]
Ah, sounds like a good bug I'll take a look today. Thanks!

**Comment by mitchellh** [comment]
Got it fixed :)

**Comment by emilevauge** [comment]
Thanks for the quick fix @mitchellh 👍

**Comment by emilevauge** [comment]
Thanks for the quick fix @mitchellh 👍
