### ISSUE TITLE
Method to handle URL.Query()

### ISSUE THREAD

**Issue by lcustodio** [mitchellh/mapstructure#58]
It would be awesome if the library supported a straight forward mapping from [URL.Query()](https://golang.org/pkg/net/url/#URL.Query) from the standard library.

Query() returns a map like:
`map[a:[aaaa] b:[bbbb] c:[cccc]]`

And as expected I get type error: `A' expected type 'string', got unconvertible type '[]string'`

The struct looks like:

```
type Measure struct {
	A    string
	B    string
	C   string
}
```

*I've no idea why URL.Query returns a map with array elements inside tough. (well.. I know [why](https://golang.org/pkg/net/url/#Values) but a GET is not likely to have duplicated params)

**Comment by lcustodio** [comment]
http -> url

**Comment by mitchellh** [comment]
If you decode into weak types or write a custom decode func you can do this.
