### ISSUE TITLE
XML and JSON tag support

### ISSUE THREAD

**Issue by AlskiOnTheWeb** [mitchellh/mapstructure#59]
It'd be nice if there were a way to tell the codec to use the stock JSON or XML tags for writing or reading it's data. We find a lot of times moving from JSON where the names are mapped, we have to duplicate the JSON tags to mapstructure tags to get the desired results. A nice configuration option would be to tell the coded the tag type to honor.

**Comment by mourad** [comment]
I had the need for the same thing, and it worked if you define the `DecoderConfig.TagName` to be, for example, `"json"`.  Quick example of what worked for me:

```
	config := &DecoderConfig{
		Metadata: nil,
		Result:   &result,
		TagName:  "json",
	}
	decoder, err := NewDecoder(config)
	if err != nil {
		panic(err)
	}

	err = decoder.Decode(input)
 	if err != nil {
		panic(err)
	}
```

**Comment by mitchellh** [comment]
Ah sorry I thought I responded to this with exactly what @mourad said. :) 

We specifically allow configuring the tag for this reason. I don't think it makes sense for us to assume you want the same structure across both by default.
