### ISSUE TITLE
Would you be open to support array types?

### ISSUE THREAD

**Issue by calvinchengx** [mitchellh/mapstructure#69]
I have added in a case to handle array type because I need to deal with `uuid.UUID` type

```
	var err error
	dataKind := getKind(val)
	fmt.Println(name, val, dataKind)
	switch dataKind {
	case reflect.Bool:
		err = d.decodeBool(name, data, val)
	case reflect.Interface:
		err = d.decodeBasic(name, data, val)
	case reflect.String:
		err = d.decodeString(name, data, val)
	case reflect.Int:
		err = d.decodeInt(name, data, val)
	case reflect.Uint:
		err = d.decodeUint(name, data, val)
	case reflect.Float32:
		err = d.decodeFloat(name, data, val)
	case reflect.Struct:
		err = d.decodeStruct(name, data, val)
	case reflect.Map:
		err = d.decodeMap(name, data, val)
	case reflect.Ptr:
		err = d.decodePtr(name, data, val)
	case reflect.Slice:
		err = d.decodeSlice(name, data, val)
	case reflect.Array: // required to handle uuid.UUID type
		err = d.decodeArray(name, data, val)
	default:
		// If we reached this point then we weren't able to decode it
		return fmt.Errorf("%s: unsupported type: %s", name, dataKind)
	}
```

Would you accept this new feature?

**Comment by mitchellh** [comment]
Yep!

**Comment by xming13** [comment]
May I know what is the status for this?

**Comment by calvinchengx** [comment]
@xming13 I must have sorted it out on my local/own project but have not made a pull request. Will check and get back to you ASAP. Completely forgotten about it. My bad.

**Comment by xming13** [comment]
@calvinchengx that's great! Thanks in advance :)

**Comment by mrviru** [comment]
@mitchellh

gocassa package depends on your package. But since your package doesn't have support for Array decoding, UUID type unmarshalling not working in gocassa. Cassandra heavily uses UUID types.

https://github.com/gocassa/gocassa/issues/158

It would be awesome, if you include Array support.

@calvinchengx

Hi mate, Can you give us the rest of the code?  decodeArray part?

Thanks

**Comment by gazoon** [comment]
Cool feature!

**Comment by Linuturk** [comment]
Wanted to :+1: this need. Hope this gets merged soon @mitchellh
