### ISSUE TITLE
Add support for field name remapping hook

### ISSUE THREAD

**Issue by oakad** [mitchellh/mapstructure#89]
Currently, if I'm not mistaken, the only way to reconcile input data field names and destination struct field names is to use annotations on destination struct's fields.

It will be convenient, if it was possible to have a hook function which will return possible alternative names for any given source/destination field name (either one appears to be enough). There exist many common cases for such functionality, examples being underscore delimited to camel case translation, unicode/punicode encoding handling, various escaped strings and so on.

**Comment by preslavrachev** [comment]
Does anyone mind pointing out how it works through struct annotations? I could not find it after a quick glance of the docs, and I am lazy enough to look it up in the code.

**Comment by oakad** [comment]
https://godoc.org/github.com/mitchellh/mapstructure#ex-Decode--Tags
